### ISSUE TITLE
Logo is almost invisible on dark mode themes

### ISSUE THREAD

**Issue by piratecarrot** [Mobject-Dev-Team/mobject.org#1]
This applies to all the subsites
https://www.stefanjudis.com/notes/how-to-define-dark-light-mode-images-in-github-markdown/

![mobject-screenshot-dark-logo](https://user-images.githubusercontent.com/39475419/233297008-80b708ac-b469-47c6-a1d1-f71a70175873.PNG)

**Comment by benhar-dev** [comment]
Thank you @piratecarrot, this has now been implemented on the main site and mobject-disposable.  The other pages will update shortly.

As an extra, we now fully support dark mode on the docsify site too.  I hope you like this feature.
