### ISSUE TITLE
Publish on Twinpack

### ISSUE THREAD

**Issue by beslst** [Mobject-Dev-Team/mobject.org#2]
Hi! We implemented a package manager for TwinCAT, similarly to nuget.

https://github.com/zeugwerk/twinpack

It is integrated in TcXAEShell and Visual Studio and also offers a simple command line interface for downloading and uploading packages on CI environments so it can even be used in your latest efforts to implement a github action for building a PLC project (btw. if you want to do some discussions on this, we have something pretty similar where a scaling building envionrment is hosted by us or our customers, https://github.com/Zeugwerk/zkbuild-action). Ultimately we want to make DevOps more accessible in the PLC world and having an open source package manager is our first step towards this goal.

Would you upload the mobject libraries to Twinpack to facility the installation of it for TwinCAT users?

**Comment by benhar-dev** [comment]
Hi @iadonkey, thank you for reaching out.  I have been following along with Twinpack which is looking promising.  Yes, I think this will be possible.  We are currently working on the CI/CD pipeline for this library. Once this is complete we will look to add the twinpack deployment action.

**Comment by beslst** [comment]
Great thanks! We actually just implemented https://github.com/Zeugwerk/twinpack-action to showcase how to use the commandline interface to upload to Twinpack and automate it easy for people that release on GitHub.

If you want to, you are also welcome to use https://github.com/Zeugwerk/zkbuild-action - It takes care of restoring third-party libraries (if available on Twinpack) , building, testing (limited to Zeugwerks workflow though atm) and is running on a scaling-, virtual environment. For open source projects we offer 30 actions of zkbuild and zkdoc for free. Demos for the action can be found here: https://github.com/stefanbesler/struckig/actions if you are interested

But maybe you want your own solution to showcase people how to achieve something like that on their self-hosted environment?

**Comment by benhar-dev** [comment]
I'll close the issue for now, but will be back to this in the new year. 👍
